apiVersion: v1
kind: Secret
metadata:
  name: cloud-controller-manager
  namespace: kube-system
type: Opaque
stringData:
  azure.json: |
    {
      "cloud": "AzurePublicCloud",
      "tenantId": "",
      "subscriptionId": "",
      "resourceGroup": "",
      "location": "",
      "subnetName": "",
      "securityGroupName": "",
      "vnetName": "",
      "vnetResourceGroup": "",
      "routeTableName": "",
      "primaryAvailabilitySetName": "",
      "primaryScaleSetName": "",
      "cloudProviderBackoffMode": "v2",
      "cloudProviderBackoff": true,
      "cloudProviderBackoffRetries": 6,
      "cloudProviderBackoffDuration": 5,
      "cloudProviderRateLimit": true,
      "cloudProviderRateLimitQPS": 10,
      "cloudProviderRateLimitBucket": 100,
      "cloudProviderRateLimitQPSWrite": 10,
      "cloudProviderRateLimitBucketWrite": 100,
      "useManagedIdentityExtension": true,
      "useInstanceMetadata": true,
      "loadBalancerSku": "standard",
      "excludeMasterFromStandardLB": true,
      "disableOutboundSNAT": false,
      "maximumLoadBalancerRuleCount": 250,
      "disableLoadBalancerFloatingIP": false
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-cloud-controller-manager
  namespace: kube-system
  labels:
    tier: control-plane
    k8s-app: azure-cloud-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: azure-cloud-controller-manager
  template:
    metadata:
      labels:
        tier: control-plane
        k8s-app: azure-cloud-controller-manager
    spec:
      serviceAccountName: cloud-controller-manager
      tolerations:
      - key: node.cloudprovider.kubernetes.io/uninitialized
        value: "true"
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      containers:
      - name: azure-cloud-controller-manager
        image: mcr.microsoft.com/oss/kubernetes/azure-cloud-controller-manager:v1.27.0
        command:
        - /usr/local/bin/azure-cloud-controller-manager
        - --v=3
        - --cloud-config=/etc/kubernetes/azure.json
        - --cloud-provider=azure
        - --use-service-account-credentials=true
        - --allocate-node-cidrs=true
        - --configure-cloud-routes=true
        - --controllers=*,-route
        - --leader-elect=true
        - --leader-elect-lease-duration=15s
        - --leader-elect-renew-deadline=10s
        - --leader-elect-retry-period=2s
        volumeMounts:
        - name: cloud-config
          mountPath: /etc/kubernetes
          readOnly: true
      volumes:
      - name: cloud-config
        secret:
          secretName: cloud-controller-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cloud-controller-manager
  namespace: kube-system
  labels:
    k8s-app: azure-cloud-controller-manager 